#!/bin/bash
SESSION=`basename $PWD | sed 's/[^a-zA-Z0-9]//g'`

tmux -2 new-session -d -s $SESSION

tmux rename-window -t $SESSION:1 vim
tmux split-window -p 25
tmux select-pane -t 0
tmux new-window -t $SESSION -a -n git
tmux split-window   -h

tmux select-window -t $SESSION:1
tmux -2 attach -t $SESSION
