#!/bin/bash
SESSION=`basename $PWD`

tmux -2 new-session -d -s $SESSION

tmux rename-window -t $SESSION:1 vim
tmux split-window   -h
tmux select-pane -t 0
tmux resize-pane -R 30
tmux split-window -p 25
tmux new-window -t $SESSION -a -n git

tmux select-window -t $SESSION:1
tmux -2 attach -t $SESSION
